baseURL = "https://doomcoin.netlify.app/"
languageCode = "en"
disableKinds = ["taxonomy"]

[build]
    writeStats = true

[params]
    title = "CRYPTO DOOM COIN"
    author = "DR DOOM"
    description = "HUMANITY IS IN DANGER"
    copyright = "Custom copyright message"
    theme = "dark" # `dark` or `light`
    

    # Profile section
    [params.profile]
        name = "DOOM Coin"
        title = "crypto"
        photo = "images/doom.jpg"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
        icon = "fab fa-telegram"
        url = "https://t.me/doomcoin1"
        title = "telegram"

        [[params.social.list]]
        icon = "fab fa-twitter"
        url = "https://x.com/DOOM"
        title = "twitter"
		

    # Education section
    [params.education]
        title = "Support"

        [[params.education.list]]
        degree = "Huge community of DOOM players in the world"
        college = "Game series"
        dates = "1993 - 2025"
        thesis_title = "More than 10 million people worldwide"
        thesis_link = "#"




    # Interests section
    [params.hobbies]
        title = "Doom Coin Properties"

        [[params.hobbies.list]]
        interest = "-The power of friendship"
		
		[[params.hobbies.list]]
        interest = "-Growth rate"

        [[params.hobbies.list]]
        interest = "-Resistance to Evil"

        [[params.hobbies.list]]
        interest = "-Joint efforts"

    [params.aboutme]
        description = "Demonic activity has been detected on the moon! The Doom Slayer is currently in another dimension! By purchasing Doom Coin, we can work together to open a portal and send DOOM Coin TO THE MOON !!!"

    # Experiences section
    [params.experiences]
        title = "Inspiration"

        [[params.jobs.list]]
        
        dates = "26.12.2024"
		link = "#"
        company = "Doom Slayer"
         details = "In these difficult times, such a strong and courageous hero as the Doom Slayer was sorely lacking. After all, he alone confronts the enormous evil and horror of hell!"

        [[params.jobs.list]]
        
        dates = "26.12.2024"
		link = "#"
        company = "DOOM Coin"
        details = "This beautiful crypto coin is designed to support the fighter against evil, the guy from Doom. We, ordinary people, can do our part to defeat the forces of evil."

    # Projects section
    [params.projects]
        title = "TOKEN INFORMATION"

        [[params.projects.list]]
        title = "*SMART CONTRACT*"
        url = "https://pump.fun/coin/Gug4gvHWXECvcRYJBh4NbHd2MqEYWwjZxdt7n2tnpump"
        description = "Gug4gvHWXECvcRYJBh4NbHd2MqEYWwjZxdt7n2tnpump"
		
		[[params.projects.list]]
        title = "*TOKEN AMOUNT*"
        url = "https://pump.fun/coin/Gug4gvHWXECvcRYJBh4NbHd2MqEYWwjZxdt7n2tnpump"
        description = "1 000 000 000"

    # Skills section
    [params.skills]
        title = "Market Cap"

        [[params.skills.list]]
        skill = "Target 3 - 300k"
        skillrating = 88
                
        [[params.skills.list]]
        skill = "Target 2 - 130k"
        skillrating = 50
		
        [[params.skills.list]]
        skill = "Target 1 - 50k"
        skillrating = 15