[build]
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "0.123.8"
  NODE_VERSION = "18"


[[redirects]]
  from = "https://doomcoin.netlify.app/:splat"
  to = "https://doomcoin.netlify.app/:splat"
  status = 301
  force = true

